/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SiteTheme = {
  _id: string;
  _type: "siteTheme";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  colorPrimary?: Color;
  colorPrimaryHover?: Color;
  colorPrimaryForeground?: Color;
  colorBackground?: Color;
  colorSurface?: Color;
  colorForeground?: Color;
  colorMuted?: Color;
  colorBorder?: Color;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  siteDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socials?: {
    instagram?: string;
    facebook?: string;
    linkedin?: string;
    tiktok?: string;
  };
  contactEmail?: string;
  analyticsId?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  copyright?: string;
};

export type Navbar = {
  _id: string;
  _type: "navbar";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  links?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  cta?: Cta;
};

export type EmailBlast = {
  _id: string;
  _type: "emailBlast";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  subject: string;
  previewText?: string;
  body: string;
  status?: "draft" | "sent";
  sentAt?: string;
};

export type Subscriber = {
  _id: string;
  _type: "subscriber";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  email: string;
  subscribedAt?: string;
  status?: "active" | "unsubscribed";
};

export type ClassRegistration = {
  _id: string;
  _type: "classRegistration";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  classKey?: string;
  className?: string;
  classDate?: string;
  name?: string;
  email?: string;
  cancelToken?: string;
  status?: "active" | "cancelled";
  createdAt?: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  contactDetail?: ContactDetail;
  contactForm?: ContactForm;
  seo?: Seo;
};

export type TestimonialsPage = {
  _id: string;
  _type: "testimonialsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  testimonialGrid?: TestimonialGrid;
  ctaBanner?: TestimonialsCtaBanner;
  seo?: Seo;
};

export type ClassesPage = {
  _id: string;
  _type: "classesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  classList?: ClassList;
  newsletterSignup?: NewsletterSignup;
  seo?: Seo;
};

export type ServicesPage = {
  _id: string;
  _type: "servicesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  serviceCards?: ServiceCards;
  faq?: Faq;
  seo?: Seo;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: HeroAbout;
  philosophy?: Philosophy;
  certifications?: Certifications;
  testimonialQuote?: TestimonialQuote;
  ctaBanner?: CtaBanner;
  seo?: Seo;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero?: Hero;
  editorialBlock?: EditorialBlock;
  featureGrid?: FeatureGrid;
  testimonialQuote?: TestimonialQuote;
  seo?: Seo;
};

export type ContactForm = {
  _type: "contactForm";
  heading: string;
  buttonLabel?: string;
  subjectOptions?: Array<{
    label?: string;
    value?: string;
    _key: string;
  }>;
};

export type ContactDetail = {
  _type: "contactDetail";
  overline?: string;
  headline: string;
  headlineEmphasis?: string;
  body?: string;
  contactMethods: Array<{
    icon?: string;
    label?: string;
    value?: string;
    url?: string;
    _key: string;
  }>;
  image?: ImageWithAlt;
  pullQuote?: string;
};

export type TestimonialsCtaBanner = {
  _type: "testimonialsCtaBanner";
  heading: string;
  body?: string;
  primaryCta?: Cta;
  secondaryCta?: Cta;
};

export type TestimonialGrid = {
  _type: "testimonialGrid";
  testimonials?: Array<{
    overline?: string;
    rating?: number;
    quote: string;
    body?: string;
    attribution?: string;
    attributionDetail?: string;
    variant: "asymmetric" | "editorial" | "gallery";
    images?: Array<{
      _key: string;
    } & ImageWithAlt>;
    _key: string;
  }>;
};

export type NewsletterSignup = {
  _type: "newsletterSignup";
  heading: string;
  body?: string;
  buttonLabel?: string;
};

export type ClassList = {
  _type: "classList";
  classes?: Array<{
    title: string;
    date?: string;
    time?: string;
    location?: string;
    description?: string;
    price?: string;
    ctaLabel?: string;
    ctaUrl?: string;
    attendeeLimit?: number;
    _key: string;
  }>;
};

export type Faq = {
  _type: "faq";
  heading?: string;
  faqs?: Array<{
    question: string;
    answer: string;
    _key: string;
  }>;
};

export type ServiceCards = {
  _type: "serviceCards";
  packages?: Array<{
    package: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "servicePackage";
    };
    variant: "featured" | "compact" | "highlighted" | "media";
    _key: string;
  }>;
};

export type ServicePackage = {
  _id: string;
  _type: "servicePackage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  icon?: string;
  tagline?: string;
  summary: string;
  pullQuote?: string;
  heroImage?: ImageWithAlt;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  features?: Array<string>;
  pricingLabel?: string;
  pricing?: string;
  sessions?: Array<{
    duration?: string;
    label?: string;
    _key: string;
  }>;
  ctaLabel?: string;
  seo?: Seo;
};

export type CtaBanner = {
  _type: "ctaBanner";
  image?: ImageWithAlt;
  heading: string;
  headlineEmphasis?: string;
  body?: string;
  primaryCta?: Cta;
  secondaryCta?: Cta;
};

export type Certifications = {
  _type: "certifications";
  heading: string;
  subheading?: string;
  items?: Array<{
    icon?: string;
    title: string;
    description?: string;
    certFile?: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
      };
      media?: unknown;
      _type: "file";
    };
    certUrl?: string;
    _type: "certificationItem";
    _key: string;
  }>;
};

export type Philosophy = {
  _type: "philosophy";
  heading: string;
  body: string;
  pullQuote?: string;
};

export type HeroAbout = {
  _type: "heroAbout";
  overline?: string;
  headline: string;
  headlineEmphasis?: string;
  body: string;
  image?: ImageWithAlt;
};

export type TestimonialQuote = {
  _type: "testimonialQuote";
  quote: string;
  attribution?: string;
  image?: ImageWithAlt;
  hasPillBackground?: boolean;
};

export type FeatureGrid = {
  _type: "featureGrid";
  overline?: string;
  heading: string;
  features?: Array<{
    icon?: string;
    title: string;
    description?: string;
    linkLabel?: string;
    linkUrl?: string;
    _key: string;
  }>;
};

export type EditorialBlock = {
  _type: "editorialBlock";
  heading: string;
  body: string;
  highlightText?: string;
  pullQuote?: string;
  image?: ImageWithAlt;
};

export type Hero = {
  _type: "hero";
  overline?: string;
  headline: string;
  body?: string;
  headlineEmphasis?: string;
  image?: ImageWithAlt;
  accentImage?: ImageWithAlt;
  primaryCta?: Cta;
  secondaryCta?: Cta;
  compact?: boolean;
};

export type PortableTextBlock = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
  caption?: string;
  _type: "image";
  _key: string;
}>;

export type ImageWithAlt = {
  _type: "imageWithAlt";
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt: string;
  caption?: string;
};

export type Seo = {
  _type: "seo";
  title?: string;
  description?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Cta = {
  _type: "cta";
  label: string;
  url: string;
  newTab?: boolean;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = SiteTheme | SiteSettings | Footer | Navbar | EmailBlast | Subscriber | ClassRegistration | ContactPage | TestimonialsPage | ClassesPage | ServicesPage | AboutPage | HomePage | ContactForm | ContactDetail | TestimonialsCtaBanner | TestimonialGrid | NewsletterSignup | ClassList | Faq | ServiceCards | ServicePackage | CtaBanner | Certifications | Philosophy | HeroAbout | TestimonialQuote | FeatureGrid | EditorialBlock | Hero | PortableTextBlock | ImageWithAlt | Seo | Cta | Color | RgbaColor | HsvaColor | HslaColor | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
